# Generated by Django 3.2 on 2022-02-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customproductsitem_todolistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproducts',
            name='img',
        ),
    ]
