# Generated by Django 3.2 on 2022-02-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220207_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
