# Generated by Django 3.2 on 2022-02-06 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_customusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproducts',
            name='seller',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
