# Generated by Django 3.2 on 2022-02-06 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_myproducts_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproducts',
            name='seller',
        ),
        migrations.AddField(
            model_name='myproducts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
