# Generated by Django 3.2 on 2022-02-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_myproducts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproducts',
            name='img',
        ),
    ]
